export const AlgebraAdvanceMathsPuzzles = [
    {
        id: 'puzzle-44',
        name: 'X Hunter',
        icon: '❓',
        description: 'Track down missing values in equations',
        category: 'Algebra',
        subCategory: 'Algebra',
        path: '/all-puzzles/algebra-advance-maths-puzzles/xHunter',
        slug: 'solve-for-x',
        difficulty: 'Medium',
        createdAt: new Date('2025-02-27'),
    },
    {
        id: 'puzzle-45',
        name: 'Polynomial Puzzle',
        icon: '📈',
        description: 'Arrange polynomial patterns',
        category: 'Algebra',
        subCategory: 'Algebra',
        path: '/all-puzzles/algebra-advance-maths-puzzles/polynomial',
        slug: 'polynomial-puzzler',
        difficulty: 'Hard',
        createdAt: new Date('2025-02-28'),
    },
    {
        id: 'puzzle-46',
        name: 'Matrix Master',
        icon: '🔢',
        description: 'Solve number grid mysteries',
        category: 'Algebra',
        subCategory: 'Algebra',
        path: '/all-puzzles/algebra-advance-maths-puzzles/matrixMaster',
        slug: 'matrix-madness',
        difficulty: 'Hard',
        createdAt: new Date('2025-03-01'),
    },
    {
        id: 'puzzle-47',
        name: 'Vector Voyage',
        icon: '➡️',
        description: 'Navigate using vector directions',
        category: 'Algebra',
        subCategory: 'Physics',
        path: '/all-puzzles/algebra-advance-maths-puzzles/vectorVoyage',
        slug: 'vector-quest',
        difficulty: 'Medium',
        createdAt: new Date('2025-03-02'),
    },
    {
        id: 'puzzle-48',
        name: 'Calculus Race',
        icon: '🏎️',
        description: 'Speed through derivative challenges',
        category: 'Algebra',
        subCategory: 'Calculus',
        path: '/all-puzzles/algebra-advance-maths-puzzles/calculusRace',
        slug: 'derivative-dash',
        difficulty: 'Hard',
        createdAt: new Date('2025-03-03'),
    },
    {
        id: 'puzzle-49',
        name: 'Pi Memory Challenge',
        icon: '🥧',
        description: 'Memorize the magic of Pi digits',
        category: 'Algebra',
        subCategory: 'Memory',
        path: '/all-puzzles/algebra-advance-maths-puzzles/piMemory',
        slug: 'pi-game',
        difficulty: 'Medium',
        createdAt: new Date('2025-03-04'),
    }
]