export const AllMathsPuzzles =[
   
        {
            id: 'puzzle-9',
            name: 'Divisibility Challenge',
            icon: '⏱️',
            description: 'Race against time with division',
            subCategory: 'Speed',
            category: 'Number Logic',
            path: '/all-puzzles/number-logic-puzzles/divisibilityChallenge',
            slug: 'divisibility',
            difficulty: 'Hard', // Added difficulty
            createdAt: new Date('2025-01-23'),
        },
        {
            id: 'puzzle-2',
            name: 'Number Maze',
            icon: '🌀',
            description: 'Navigate mazes with math solutions',
            subCategory: 'Adventure',
            category: 'Number Logic',
            path: '/all-puzzles/number-logic-puzzles/numberMaze',
            slug: 'number-maze',
            difficulty: 'Medium', // Added difficulty
            createdAt: new Date('2025-01-16'),
        },
        {
            id: 'puzzle-3',
            name: 'Magic Square',
            icon: '🔮',
            description: 'Create magical number patterns',
            subCategory: 'Puzzles',
            category: 'Number Logic',
            path: '/all-puzzles/number-logic-puzzles/magicSquare',
            slug: 'magic-square',
            difficulty: 'Hard', // Added difficulty
            createdAt: new Date('2025-01-17'),
        },
        {
            id: 'puzzle-4',
            name: 'Math Crosswords',
            icon: '➕',
            description: 'Solve equation crossword puzzles',
            subCategory: 'Wordplay',
            category: 'Number Logic',
            path: '/all-puzzles/number-logic-puzzles/mathCrosswords',
            slug: 'math-crosswords',
            difficulty: 'Medium', // Added difficulty
            createdAt: new Date('2025-01-18'),
        },
        {
            id: 'puzzle-5',
            name: 'Number Sequence',
            icon: '🔢',
            description: 'Discover pattern mysteries',
            subCategory: 'Patterns',
            category: 'Number Logic',
            path: '/all-puzzles/number-logic-puzzles/numberSequence',
            slug: 'number-sequence',
            difficulty: 'Easy', // Added difficulty
            createdAt: new Date('2025-01-19'),
        },
        // {
        //     id: 'puzzle-6',
        //     name: 'Math Riddle Adventure',
        //     icon: '🧙♂️',
        //     description: 'Solve riddles to unlock treasures',
        //     subCategory: 'Adventure',
        //     category: 'Number Logic',
        //     path: '/all-puzzles/number-logic-puzzles/mathRiddle',
        //     slug: 'math-riddle',
        //     difficulty: 'Medium', // Added difficulty
        //     createdAt: new Date('2025-01-20'),
        // },
        {
            id: 'puzzle-7',
            name: 'Math Word Search',
            icon: '🔍',
            description: 'Find hidden math terms',
            subCategory: 'Wordplay',
            category: 'Number Logic',
            path: '/all-puzzles/number-logic-puzzles/mathWordSearch',
            slug: 'word-search',
            difficulty: 'Easy', // Added difficulty
            createdAt: new Date('2025-01-21'),
        },
        {
            id: 'puzzle-8',
            name: 'Prime Number Hunt',
            icon: '🎯',
            description: 'Hunt for special prime numbers',
            subCategory: 'Numbers',
            category: 'Number Logic',
            path: '/all-puzzles/number-logic-puzzles/primeNumberHunt',
            slug: 'prime-hunt',
            difficulty: 'Hard', // Added difficulty
            createdAt: new Date('2025-01-22'),
        },
            {
                id: 'puzzle-44',
                name: 'X Hunter',
                icon: '❓',
                description: 'Track down missing values in equations',
                category: 'Algebra',
                subCategory: 'Algebra',
                path: '/puzzles/solve-for-x',
                slug: 'solve-for-x',
                difficulty: 'Medium',
                createdAt: new Date('2025-02-27'),
            },
            {
                id: 'puzzle-45',
                name: 'Polynomial Puzzle',
                icon: '📈',
                description: 'Arrange polynomial patterns',
                category: 'Algebra',
                subCategory: 'Algebra',
                path: '/puzzles/polynomial-puzzler',
                slug: 'polynomial-puzzler',
                difficulty: 'Hard',
                createdAt: new Date('2025-02-28'),
            },
            {
                id: 'puzzle-46',
                name: 'Matrix Master',
                icon: '🔢',
                description: 'Solve number grid mysteries',
                category: 'Algebra',
                subCategory: 'Algebra',
                path: '/puzzles/matrix-madness',
                slug: 'matrix-madness',
                difficulty: 'Hard',
                createdAt: new Date('2025-03-01'),
            },
            {
                id: 'puzzle-47',
                name: 'Vector Voyage',
                icon: '➡️',
                description: 'Navigate using vector directions',
                category: 'Algebra',
                subCategory: 'Physics',
                path: '/puzzles/vector-quest',
                slug: 'vector-quest',
                difficulty: 'Medium',
                createdAt: new Date('2025-03-02'),
            },
            {
                id: 'puzzle-48',
                name: 'Calculus Race',
                icon: '🏎️',
                description: 'Speed through derivative challenges',
                category: 'Algebra',
                subCategory: 'Calculus',
                path: '/puzzles/derivative-dash',
                slug: 'derivative-dash',
                difficulty: 'Hard',
                createdAt: new Date('2025-03-03'),
            },
            {
                id: 'puzzle-49',
                name: 'Pi Memory Challenge',
                icon: '🥧',
                description: 'Memorize the magic of Pi digits',
                category: 'Algebra',
                subCategory: 'Memory',
                path: '/puzzles/pi-game',
                slug: 'pi-game',
                difficulty: 'Medium',
                createdAt: new Date('2025-03-04'),
            },
            {
                id: 'puzzle-15',
                name: 'Mental Math Race',
                icon: '🏁',
                description: 'Speed through arithmetic challenges',
                category: 'Arithmetic Calculation',
                subCategory: 'Arithmetic',
                path: '/puzzles/math-race',
                slug: 'math-race',
                difficulty: 'Hard',
                createdAt: new Date('2025-01-29'),
            },
            {
                id: 'puzzle-16',
                name: 'Equation Balancer',
                icon: '⚖️',
                description: 'Balance magical math equations',
                category: 'Arithmetic Calculation',
                subCategory: 'Algebra',
                path: '/puzzles/equation-balancer',
                slug: 'equation-balancer',
                difficulty: 'Medium',
                createdAt: new Date('2025-01-30'),
            },
            {
                id: 'puzzle-17',
                name: 'Math Grid Puzzle',
                icon: '🔳',
                description: 'Solve number grid mysteries',
                category: 'Arithmetic Calculation',
                subCategory: 'Logic',
                path: '/puzzles/grid-puzzle',
                slug: 'grid-puzzle',
                difficulty: 'Hard',
                createdAt: new Date('2025-01-31'),
            },
            {
                id: 'puzzle-18',
                name: 'Fraction Challenge',
                icon: '🍕',
                description: 'Slice and compare pizza fractions',
                category: 'Arithmetic Calculation',
                subCategory: 'Fractions',
                path: '/puzzles/fraction-challenge',
                slug: 'fraction-challenge',
                difficulty: 'Medium',
                createdAt: new Date('2025-02-01'),
            },
            {
                id: 'puzzle-19',
                name: 'Multiplication Tower',
                icon: '🏰',
                description: 'Build towers with times tables',
                category: 'Arithmetic Calculation',
                subCategory: 'Arithmetic',
                path: '/puzzles/multiplication-tower',
                slug: 'multiplication-tower',
                difficulty: 'Easy',
                createdAt: new Date('2025-02-02'),
            },
            {
                id: 'puzzle-10',
                name: 'Tangram Challenge',
                icon: '🧩',
                description: 'Arrange shapes to create magical figures',
                category: 'Geometry Spatial',
                subCategory: 'Geometry',
                path: '/puzzles/tangram',
                slug: 'tangram',
                difficulty: 'Medium',
                createdAt: new Date('2025-01-24'),
            },
            {
                id: 'puzzle-11',
                name: 'Shape Matcher',
                icon: '📐',
                description: 'Fit puzzle pieces into perfect spaces',
                category: 'Geometry Spatial',       
                subCategory: 'Geometry',
                path: '/puzzles/shape-matcher',
                slug: 'shape-matcher',
                difficulty: 'Easy',
                createdAt: new Date('2025-01-25'),
            },
            {
                id: 'puzzle-12',
                name: 'Angle Hunter',
                icon: '📏',
                description: 'Find hidden angles in mysterious shapes',
                category: 'Geometry Spatial',
                subCategory: 'Geometry',
                path: '/puzzles/angle-hunter',
                slug: 'angle-hunter',
                difficulty: 'Medium',
                createdAt: new Date('2025-01-26'),
            },
            {
                id: 'puzzle-13',
                name: 'Mirror Reflection Game',
                icon: '🪞',
                description: 'Predict mirror images of magical objects',
                category: 'Geometry Spatial',
                subCategory: 'Geometry',
                path: '/puzzles/mirror-game',
                slug: 'mirror-game',
                difficulty: 'Hard',
                createdAt: new Date('2025-01-27'),
            },
            {
                id: 'puzzle-14',
                name: '3D Cube Stacking',
                icon: '🟦',
                description: 'Build towering structures with cubes',
                category: 'Geometry Spatial',
                subCategory: 'Spatial',
                path: '/puzzles/cube-stacking',
                slug: 'cube-stacking',
                difficulty: 'Medium',
                createdAt: new Date('2025-01-28'),
            },
            {
                id: 'puzzle-30',
                name: 'Coordinate Battles',
                icon: '🏴☠️',
                description: 'Battle pirates using coordinate skills',
                category: 'Graph Coordinate Based',
                subCategory: 'Geometry',
                path: '/puzzles/coordinate-battles',
                slug: 'coordinate-battles',
                difficulty: 'Medium',
                createdAt: new Date('2025-02-13'),
            },
            {
                id: 'puzzle-31',
                name: 'Math Treasure Hunt',
                icon: '🗺️',
                description: 'Follow maps to discover math treasures',
                category: 'Graph Coordinate Based',
                subCategory: 'Adventure',
                path: '/puzzles/treasure-hunt',
                slug: 'treasure-hunt',
                difficulty: 'Easy',
                createdAt: new Date('2025-02-14'),
            },
            {
                id: 'puzzle-32',
                name: 'Network Navigator',
                icon: '🧠',
                description: 'Solve connection mysteries in networks',
                category: 'Graph Coordinate Based',
                subCategory: 'Logic',
                path: '/puzzles/graph-theory',
                slug: 'graph-theory',
                difficulty: 'Hard',
                createdAt: new Date('2025-02-15'),
            },
            {
                id: 'puzzle-33',
                name: 'Equation Launcher',
                icon: '🚀',
                description: 'Launch rockets by graphing equations',
                category: 'Graph Coordinate Based',
                subCategory: 'Algebra',
                path: '/puzzles/equation-plotter',
                slug: 'equation-plotter',
                difficulty: 'Medium',
                createdAt: new Date('2025-02-16'),
            },
            {
                id: 'puzzle-34',
                name: 'Weight Wizard',
                icon: '⚖️',
                description: 'Guess magical object weights',
                category: 'Measurement Estimation',
                subCategory: 'Measurement',
                path: '/puzzles/weight-guess',
                slug: 'weight-guess',
                difficulty: 'Medium',
                createdAt: new Date('2025-02-17'),
            },
            {
                id: 'puzzle-35',
                name: 'Volume Voyage',
                icon: '🪣',
                description: 'Fill containers with liquid magic',
                category: 'Measurement Estimation', 
                subCategory: 'Measurement',
                path: '/puzzles/volume-puzzle',
                slug: 'volume-puzzle',
                difficulty: 'Hard',
                createdAt: new Date('2025-02-18'),
            },
            {
                id: 'puzzle-36',
                name: 'Time Travel Challenge',
                icon: '⏰',
                description: 'Solve clock mysteries across time zones',
                category: 'Measurement Estimation',
                subCategory: 'Time',
                path: '/puzzles/clock-challenge',
                slug: 'clock-challenge',
                difficulty: 'Medium',
                createdAt: new Date('2025-02-19'),
            },
            {
                id: 'puzzle-37',
                name: 'Distance Dash',
                icon: '🏁',
                description: 'Race to find shortest paths',
                category: 'Measurement Estimation',
                subCategory: 'Geometry',
                path: '/puzzles/distance-game',
                slug: 'distance-game',
                difficulty: 'Hard',
                createdAt: new Date('2025-02-20'),
            },
            {
                id: 'puzzle-38',
                name: 'Coin Carnival',
                icon: '💰',
                description: 'Solve money mysteries at the math fair',
                category: 'Measurement Estimation',
                subCategory: 'Money',
                path: '/puzzles/money-puzzle',
                slug: 'money-puzzle',
                difficulty: 'Medium',
                createdAt: new Date('2025-02-21'),
            },
            {
                id: 'puzzle-25',
                name: 'Pattern Detective',
                icon: '🕵️♂️',
                description: 'Uncover hidden number sequences',
                category: 'Pattern Recognition Matching',       
                subCategory: 'Patterns',
                path: '/puzzles/pattern-matching',
                slug: 'pattern-matching',
                difficulty: 'Medium',
                createdAt: new Date('2025-02-08'),
            },
            {
                id: 'puzzle-26',
                name: 'Shape Sudoku',
                icon: '🎲',
                description: 'Solve Sudoku with magical shapes',
                category: 'Pattern Recognition Matching',
                subCategory: 'Puzzles',
                path: '/puzzles/shape-sudoku',
                slug: 'shape-sudoku',
                difficulty: 'Hard',
                createdAt: new Date('2025-02-09'),
            },
            {
                id: 'puzzle-27',
                name: 'Math Jigsaw',
                icon: '🧩',
                description: 'Piece together equation puzzles',
                category: 'Pattern Recognition Matching',
                subCategory: 'Logic',
                path: '/puzzles/math-jigsaw',
                slug: 'math-jigsaw',
                difficulty: 'Medium',
                createdAt: new Date('2025-02-10'),
            },
            {
                id: 'puzzle-28',
                name: 'Magic Triangle',
                icon: '🔺',
                description: 'Balance numbers in magical triangles',
                category: 'Pattern Recognition Matching',
                subCategory: 'Geometry',
                path: '/puzzles/magic-triangle',
                slug: 'magic-triangle',
                difficulty: 'Hard',
                createdAt: new Date('2025-02-11'),
            },
            {
                id: 'puzzle-29',
                name: 'Binary Decoder',
                icon: '💻',
                description: 'Crack secret computer codes',
                category: 'Pattern Recognition Matching',
                subCategory: 'Coding',
                path: '/puzzles/binary-puzzle',
                slug: 'binary-puzzle',
                difficulty: 'Hard',
                createdAt: new Date('2025-02-12'),
            },
            {
                id: 'puzzle-20',
                name: 'Math Speed Challenge',
                icon: '⏳',
                description: 'Race against time to solve math mysteries',
                category: 'Time Based Multiplayer',
                subCategory: 'Speed',
                path: '/puzzles/speed-challenge',
                slug: 'speed-challenge',
                difficulty: 'Hard',
                createdAt: new Date('2025-02-03'),
            },
            {
                id: 'puzzle-21',
                name: 'Math Battle Arena',
                icon: '⚔️',
                description: 'Duel with friends in math showdowns',
                category: 'Time Based Multiplayer',
                subCategory: 'Multiplayer',
                path: '/puzzles/math-battle',
                slug: 'math-battle',
                difficulty: 'Medium',
                createdAt: new Date('2025-02-04'),
            },
            {
                id: 'puzzle-22',
                name: 'Escape Room Math',
                icon: '🚪',
                description: 'Solve puzzles to unlock secret rooms',
                category: 'Time Based Multiplayer',
                subCategory: 'Adventure',
                path: '/puzzles/escape-room',
                slug: 'escape-room',
                difficulty: 'Hard',
                createdAt: new Date('2025-02-05'),
            },
            {
                id: 'puzzle-23',
                name: 'Co-op Math Quest',
                icon: '🤝',
                description: 'Team up for epic math adventures',
                category: 'Time Based Multiplayer',
                subCategory: 'Multiplayer',
                path: '/puzzles/coop-quest',
                slug: 'coop-quest',
                difficulty: 'Medium',
                createdAt: new Date('2025-02-06'),
            },
            {
                id: 'puzzle-24',
                name: 'Math Board Game',
                icon: '🎲',
                description: 'Roll dice and conquer math challenges',
                category: 'Time Based Multiplayer',
                subCategory: 'Strategy',
                path: '/puzzles/board-game',
                slug: 'board-game',
                difficulty: 'Easy',
                createdAt: new Date('2025-02-07'),
            }
                 
   ]