export const ArithmeticCalculationPuzzles = [ {
    id: 'puzzle-15',
    name: 'Mental Math Race',
    icon: '🏁',
    description: 'Speed through arithmetic challenges',
    category: 'Arithmetic Calculation',
    subCategory: 'Arithmetic',
    path: '/all-puzzles/arithmetic-calculation-puzzles/mentalMath',
    slug: 'math-race',
    difficulty: 'Hard',
    createdAt: new Date('2025-01-29'),
},
{
    id: 'puzzle-16',
    name: 'Equation Balancer',
    icon: '⚖️',
    description: 'Balance magical math equations',
    category: 'Arithmetic Calculation',
    subCategory: 'Algebra',
    path: '/all-puzzles/arithmetic-calculation-puzzles/equationBalancer',
    slug: 'equation-balancer',
    difficulty: 'Medium',
    createdAt: new Date('2025-01-30'),
},
{
    id: 'puzzle-17',
    name: 'Math Grid Puzzle',
    icon: '🔳',
    description: 'Solve number grid mysteries',
    category: 'Arithmetic Calculation',
    subCategory: 'Logic',
    path: '/all-puzzles/arithmetic-calculation-puzzles/mathGridPuzzle',
    slug: 'grid-puzzle',
    difficulty: 'Hard',
    createdAt: new Date('2025-01-31'),
},
{
    id: 'puzzle-18',
    name: 'Fraction Challenge',
    icon: '🍕',
    description: 'Slice and compare pizza fractions',
    category: 'Arithmetic Calculation',
    subCategory: 'Fractions',
    path: '/all-puzzles/arithmetic-calculation-puzzles/fractionChallenge',
    slug: 'fraction-challenge',
    difficulty: 'Medium',
    createdAt: new Date('2025-02-01'),
},
{
    id: 'puzzle-19',
    name: 'Multiplication Tower',
    icon: '🏰',
    description: 'Build towers with times tables',
    category: 'Arithmetic Calculation',
    subCategory: 'Arithmetic',
    path: '/puzzles/multiplication-tower',
    slug: 'multiplication-tower',
    difficulty: 'Easy',
    createdAt: new Date('2025-02-02'),
}
]