export const GraphCoordinateBasedPuzzles = [
    {
        id: 'puzzle-30',
        name: 'Coordinate Battles',
        icon: '🏴☠️',
        description: 'Battle pirates using coordinate skills',
        category: 'Graph Coordinate Based',
        subCategory: 'Geometry',
        path: '/puzzles/coordinate-battles',
        slug: 'coordinate-battles',
        difficulty: 'Medium',
        createdAt: new Date('2025-02-13'),
    },
    {
        id: 'puzzle-31',
        name: 'Math Treasure Hunt',
        icon: '🗺️',
        description: 'Follow maps to discover math treasures',
        category: 'Graph Coordinate Based',
        subCategory: 'Adventure',
        path: '/puzzles/treasure-hunt',
        slug: 'treasure-hunt',
        difficulty: 'Easy',
        createdAt: new Date('2025-02-14'),
    },
    {
        id: 'puzzle-32',
        name: 'Network Navigator',
        icon: '🧠',
        description: 'Solve connection mysteries in networks',
        category: 'Graph Coordinate Based',
        subCategory: 'Logic',
        path: '/puzzles/graph-theory',
        slug: 'graph-theory',
        difficulty: 'Hard',
        createdAt: new Date('2025-02-15'),
    },
    {
        id: 'puzzle-33',
        name: 'Equation Launcher',
        icon: '🚀',
        description: 'Launch rockets by graphing equations',
        category: 'Graph Coordinate Based',
        subCategory: 'Algebra',
        path: '/puzzles/equation-plotter',
        slug: 'equation-plotter',
        difficulty: 'Medium',
        createdAt: new Date('2025-02-16'),
    }
]