export const MeasurementEstimationPuzzles = [
    {
        id: 'puzzle-34',
        name: 'Weight Wizard',
        icon: '⚖️',
        description: 'Guess magical object weights',
        category: 'Measurement Estimation',
        subCategory: 'Measurement',
        path: '/puzzles/weight-guess',
        slug: 'weight-guess',
        difficulty: 'Medium',
        createdAt: new Date('2025-02-17'),
    },
    {
        id: 'puzzle-35',
        name: 'Volume Voyage',
        icon: '🪣',
        description: 'Fill containers with liquid magic',
        category: 'Measurement Estimation', 
        subCategory: 'Measurement',
        path: '/puzzles/volume-puzzle',
        slug: 'volume-puzzle',
        difficulty: 'Hard',
        createdAt: new Date('2025-02-18'),
    },
    {
        id: 'puzzle-36',
        name: 'Time Travel Challenge',
        icon: '⏰',
        description: 'Solve clock mysteries across time zones',
        category: 'Measurement Estimation',
        subCategory: 'Time',
        path: '/puzzles/clock-challenge',
        slug: 'clock-challenge',
        difficulty: 'Medium',
        createdAt: new Date('2025-02-19'),
    },
    {
        id: 'puzzle-37',
        name: 'Distance Dash',
        icon: '🏁',
        description: 'Race to find shortest paths',
        category: 'Measurement Estimation',
        subCategory: 'Geometry',
        path: '/puzzles/distance-game',
        slug: 'distance-game',
        difficulty: 'Hard',
        createdAt: new Date('2025-02-20'),
    },
    {
        id: 'puzzle-38',
        name: 'Coin Carnival',
        icon: '💰',
        description: 'Solve money mysteries at the math fair',
        category: 'Measurement Estimation',
        subCategory: 'Money',
        path: '/puzzles/money-puzzle',
        slug: 'money-puzzle',
        difficulty: 'Medium',
        createdAt: new Date('2025-02-21'),
    }]