export const NumberLogicPuzzles = [
    {
        id: 'puzzle-9',
        name: 'Divisibility Challenge',
        icon: '⏱️',
        description: 'Race against time with division',
        subCategory: 'Speed',
        category: 'Number Logic',
        path: '/all-puzzles/number-logic-puzzles/divisibilityChallenge',
        slug: 'divisibility',
        difficulty: 'Hard', // Added difficulty
        createdAt: new Date('2025-01-23'),
    },
    {
        id: 'puzzle-2',
        name: 'Number Maze',
        icon: '🌀',
        description: 'Navigate mazes with math solutions',
        subCategory: 'Adventure',
        category: 'Number Logic',
        path: '/all-puzzles/number-logic-puzzles/numberMaze',
        slug: 'number-maze',
        difficulty: 'Medium', // Added difficulty
        createdAt: new Date('2025-01-16'),
    },
    {
        id: 'puzzle-3',
        name: 'Magic Square',
        icon: '🔮',
        description: 'Create magical number patterns',
        subCategory: 'Puzzles',
        category: 'Number Logic',
        path: '/all-puzzles/number-logic-puzzles/magicSquare',
        slug: 'magic-square',
        difficulty: 'Hard', // Added difficulty
        createdAt: new Date('2025-01-17'),
    },
    {
        id: 'puzzle-4',
        name: 'Math Crosswords',
        icon: '➕',
        description: 'Solve equation crossword puzzles',
        subCategory: 'Wordplay',
        category: 'Number Logic',
        path: '/all-puzzles/number-logic-puzzles/mathCrosswords',
        slug: 'math-crosswords',
        difficulty: 'Medium', // Added difficulty
        createdAt: new Date('2025-01-18'),
    },
    {
        id: 'puzzle-5',
        name: 'Number Sequence',
        icon: '🔢',
        description: 'Discover pattern mysteries',
        subCategory: 'Patterns',
        category: 'Number Logic',
        path: '/all-puzzles/number-logic-puzzles/numberSequence',
        slug: 'number-sequence',
        difficulty: 'Easy', // Added difficulty
        createdAt: new Date('2025-01-19'),
    },
    // {
    //     id: 'puzzle-6',
    //     name: 'Math Riddle Adventure',
    //     icon: '🧙♂️',
    //     description: 'Solve riddles to unlock treasures',
    //     subCategory: 'Adventure',
    //     category: 'Number Logic',
    //     path: '/all-puzzles/number-logic-puzzles/mathRiddle',
    //     slug: 'math-riddle',
    //     difficulty: 'Medium', // Added difficulty
    //     createdAt: new Date('2025-01-20'),
    // },
    {
        id: 'puzzle-7',
        name: 'Math Word Search',
        icon: '🔍',
        description: 'Find hidden math terms',
        subCategory: 'Wordplay',
        category: 'Number Logic',
        path: '/all-puzzles/number-logic-puzzles/mathWordSearch',
        slug: 'word-search',
        difficulty: 'Easy', // Added difficulty
        createdAt: new Date('2025-01-21'),
    },
    {
        id: 'puzzle-8',
        name: 'Prime Number Hunt',
        icon: '🎯',
        description: 'Hunt for special prime numbers',
        subCategory: 'Numbers',
        category: 'Number Logic',
        path: '/all-puzzles/number-logic-puzzles/primeNumberHunt',
        slug: 'prime-hunt',
        difficulty: 'Hard', // Added difficulty
        createdAt: new Date('2025-01-22'),
    },
];
