export const PatternRecognitionMatchingPuzzles = [
    {
        id: 'puzzle-25',
        name: 'Pattern Detective',
        icon: '🕵️♂️',
        description: 'Uncover hidden number sequences',
        category: 'Pattern Recognition Matching',       
        subCategory: 'Patterns',
        path: '/puzzles/pattern-matching',
        slug: 'pattern-matching',
        difficulty: 'Medium',
        createdAt: new Date('2025-02-08'),
    },
    {
        id: 'puzzle-26',
        name: 'Shape Sudoku',
        icon: '🎲',
        description: 'Solve Sudoku with magical shapes',
        category: 'Pattern Recognition Matching',
        subCategory: 'Puzzles',
        path: '/puzzles/shape-sudoku',
        slug: 'shape-sudoku',
        difficulty: 'Hard',
        createdAt: new Date('2025-02-09'),
    },
    {
        id: 'puzzle-27',
        name: 'Math Jigsaw',
        icon: '🧩',
        description: 'Piece together equation puzzles',
        category: 'Pattern Recognition Matching',
        subCategory: 'Logic',
        path: '/puzzles/math-jigsaw',
        slug: 'math-jigsaw',
        difficulty: 'Medium',
        createdAt: new Date('2025-02-10'),
    },
    {
        id: 'puzzle-28',
        name: 'Magic Triangle',
        icon: '🔺',
        description: 'Balance numbers in magical triangles',
        category: 'Pattern Recognition Matching',
        subCategory: 'Geometry',
        path: '/puzzles/magic-triangle',
        slug: 'magic-triangle',
        difficulty: 'Hard',
        createdAt: new Date('2025-02-11'),
    },
    {
        id: 'puzzle-29',
        name: 'Binary Decoder',
        icon: '💻',
        description: 'Crack secret computer codes',
        category: 'Pattern Recognition Matching',
        subCategory: 'Coding',
        path: '/puzzles/binary-puzzle',
        slug: 'binary-puzzle',
        difficulty: 'Hard',
        createdAt: new Date('2025-02-12'),
    }
] 