export const TimeBasedMultiplayerPuzzles = [{
    id: 'puzzle-20',
    name: 'Math Speed Challenge',
    icon: '⏳',
    description: 'Race against time to solve math mysteries',
    category: 'Time Based Multiplayer',
    subCategory: 'Speed',
    path: '/puzzles/speed-challenge',
    slug: 'speed-challenge',
    difficulty: 'Hard',
    createdAt: new Date('2025-02-03'),
},
{
    id: 'puzzle-21',
    name: 'Math Battle Arena',
    icon: '⚔️',
    description: 'Duel with friends in math showdowns',
    category: 'Time Based Multiplayer',
    subCategory: 'Multiplayer',
    path: '/puzzles/math-battle',
    slug: 'math-battle',
    difficulty: 'Medium',
    createdAt: new Date('2025-02-04'),
},
{
    id: 'puzzle-22',
    name: 'Escape Room Math',
    icon: '🚪',
    description: 'Solve puzzles to unlock secret rooms',
    category: 'Time Based Multiplayer',
    subCategory: 'Adventure',
    path: '/puzzles/escape-room',
    slug: 'escape-room',
    difficulty: 'Hard',
    createdAt: new Date('2025-02-05'),
},
{
    id: 'puzzle-23',
    name: 'Co-op Math Quest',
    icon: '🤝',
    description: 'Team up for epic math adventures',
    category: 'Time Based Multiplayer',
    subCategory: 'Multiplayer',
    path: '/puzzles/coop-quest',
    slug: 'coop-quest',
    difficulty: 'Medium',
    createdAt: new Date('2025-02-06'),
},
{
    id: 'puzzle-24',
    name: 'Math Board Game',
    icon: '🎲',
    description: 'Roll dice and conquer math challenges',
    category: 'Time Based Multiplayer',
    subCategory: 'Strategy',
    path: '/puzzles/board-game',
    slug: 'board-game',
    difficulty: 'Easy',
    createdAt: new Date('2025-02-07'),
}
]