export const GeometrySpatialPuzzles = [
    {
        id: 'puzzle-10',
        name: 'Tangram Challenge',
        icon: '🧩',
        description: 'Arrange shapes to create magical figures',
        category: 'Geometry',
        path: '/puzzles/tangram',
        slug: 'tangram',
        difficulty: 'Medium',
        createdAt: new Date('2025-01-24'),
    },
    {
        id: 'puzzle-11',
        name: 'Shape Matcher',
        icon: '📐',
        description: 'Fit puzzle pieces into perfect spaces',
        category: 'Geometry',
        path: '/puzzles/shape-matcher',
        slug: 'shape-matcher',
        difficulty: 'Easy',
        createdAt: new Date('2025-01-25'),
    },
    {
        id: 'puzzle-12',
        name: 'Angle Hunter',
        icon: '📏',
        description: 'Find hidden angles in mysterious shapes',
        category: 'Geometry',
        path: '/puzzles/angle-hunter',
        slug: 'angle-hunter',
        difficulty: 'Medium',
        createdAt: new Date('2025-01-26'),
    },
    {
        id: 'puzzle-13',
        name: 'Mirror Reflection Game',
        icon: '🪞',
        description: 'Predict mirror images of magical objects',
        category: 'Geometry',
        path: '/puzzles/mirror-game',
        slug: 'mirror-game',
        difficulty: 'Hard',
        createdAt: new Date('2025-01-27'),
    },
    {
        id: 'puzzle-14',
        name: '3D Cube Stacking',
        icon: '🟦',
        description: 'Build towering structures with cubes',
        category: 'Spatial',
        path: '/puzzles/cube-stacking',
        slug: 'cube-stacking',
        difficulty: 'Medium',
        createdAt: new Date('2025-01-28'),
    },
]